----adicione um usuário
--insert into tb_jogador (usuario, senha, SESSAO_STATUS) values ('admin', 'admin', false)
--insert into tb_jogador (usuario, senha, SESSAO_STATUS) values ('admin2', 'admin2', false)
----insert into tb_partidas (id, status) values (1, true)